//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Soat.HappyNet.Silverlight.Infrastructure.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringLibrary {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringLibrary() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Soat.HappyNet.Silverlight.Infrastructure.Localization.StringLibrary", typeof(StringLibrary).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HappyNet.
        /// </summary>
        public static string APP_ApplicationName {
            get {
                return ResourceManager.GetString("APP_ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuler.
        /// </summary>
        public static string APP_Cancel {
            get {
                return ResourceManager.GetString("APP_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fermer.
        /// </summary>
        public static string APP_Close {
            get {
                return ResourceManager.GetString("APP_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        public static string APP_Confirmation {
            get {
                return ResourceManager.GetString("APP_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connexion.
        /// </summary>
        public static string APP_Connect {
            get {
                return ResourceManager.GetString("APP_Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ Se déconnecter ].
        /// </summary>
        public static string APP_Disconnect {
            get {
                return ResourceManager.GetString("APP_Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mot de passe oublié ?.
        /// </summary>
        public static string APP_ForgotPassword {
            get {
                return ResourceManager.GetString("APP_ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Langue : .
        /// </summary>
        public static string APP_Language {
            get {
                return ResourceManager.GetString("APP_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string APP_OK {
            get {
                return ResourceManager.GetString("APP_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mot de passe.
        /// </summary>
        public static string APP_Password {
            get {
                return ResourceManager.GetString("APP_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S&apos;inscrire.
        /// </summary>
        public static string APP_Registration {
            get {
                return ResourceManager.GetString("APP_Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilisateur.
        /// </summary>
        public static string APP_Username {
            get {
                return ResourceManager.GetString("APP_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pour combler le vide ....
        /// </summary>
        public static string HOME_Blank {
            get {
                return ResourceManager.GetString("HOME_Blank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilisateurs contents.
        /// </summary>
        public static string HOME_HappyUsers {
            get {
                return ResourceManager.GetString("HOME_HappyUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Derniers produits à la mode.
        /// </summary>
        public static string HOME_LastProducts {
            get {
                return ResourceManager.GetString("HOME_LastProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Météo du jour.
        /// </summary>
        public static string HOME_Weather {
            get {
                return ResourceManager.GetString("HOME_Weather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panel d&apos;administration.
        /// </summary>
        public static string MENU_BackOffice {
            get {
                return ResourceManager.GetString("MENU_BackOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accueil.
        /// </summary>
        public static string MENU_Home {
            get {
                return ResourceManager.GetString("MENU_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ressources Humaines.
        /// </summary>
        public static string MENU_HumanResources {
            get {
                return ResourceManager.GetString("MENU_HumanResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commandes.
        /// </summary>
        public static string MENU_Orders {
            get {
                return ResourceManager.GetString("MENU_Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boutique.
        /// </summary>
        public static string MENU_Production {
            get {
                return ResourceManager.GetString("MENU_Production", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Détail d&apos;un employé.
        /// </summary>
        public static string PAGE_EmployeeDetails {
            get {
                return ResourceManager.GetString("PAGE_EmployeeDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste des employés.
        /// </summary>
        public static string PAGE_Employees {
            get {
                return ResourceManager.GetString("PAGE_Employees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accueil.
        /// </summary>
        public static string PAGE_Home {
            get {
                return ResourceManager.GetString("PAGE_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page introuvable.
        /// </summary>
        public static string PAGE_NotImplemented {
            get {
                return ResourceManager.GetString("PAGE_NotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commandes.
        /// </summary>
        public static string PAGE_Orders {
            get {
                return ResourceManager.GetString("PAGE_Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste des produits.
        /// </summary>
        public static string PAGE_Products {
            get {
                return ResourceManager.GetString("PAGE_Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter au panier.
        /// </summary>
        public static string PRODUCTION_AddToCart {
            get {
                return ResourceManager.GetString("PRODUCTION_AddToCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catégories.
        /// </summary>
        public static string PRODUCTION_Categories {
            get {
                return ResourceManager.GetString("PRODUCTION_Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucun produit.
        /// </summary>
        public static string PRODUCTION_NoProduct {
            get {
                return ResourceManager.GetString("PRODUCTION_NoProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Détail du produit.
        /// </summary>
        public static string PRODUCTION_ProductDetails {
            get {
                return ResourceManager.GetString("PRODUCTION_ProductDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recherche de produits....
        /// </summary>
        public static string PRODUCTION_SearchProducts {
            get {
                return ResourceManager.GetString("PRODUCTION_SearchProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher la galerie d&apos;images.
        /// </summary>
        public static string PRODUCTION_ShowGallery {
            get {
                return ResourceManager.GetString("PRODUCTION_ShowGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voir le détail.
        /// </summary>
        public static string PRODUCTION_ViewDetail {
            get {
                return ResourceManager.GetString("PRODUCTION_ViewDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payer.
        /// </summary>
        public static string SALES_Checkout {
            get {
                return ResourceManager.GetString("SALES_Checkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prix.
        /// </summary>
        public static string SALES_Cost {
            get {
                return ResourceManager.GetString("SALES_Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panier vide.
        /// </summary>
        public static string SALES_EmptyCart {
            get {
                return ResourceManager.GetString("SALES_EmptyCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produit.
        /// </summary>
        public static string SALES_Product {
            get {
                return ResourceManager.GetString("SALES_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantité.
        /// </summary>
        public static string SALES_Quantity {
            get {
                return ResourceManager.GetString("SALES_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supprimer ce produit du panier.
        /// </summary>
        public static string SALES_RemoveCartItem {
            get {
                return ResourceManager.GetString("SALES_RemoveCartItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panier d&apos;achats.
        /// </summary>
        public static string SALES_ShoppingCart {
            get {
                return ResourceManager.GetString("SALES_ShoppingCart", resourceCulture);
            }
        }
    }
}
